name: Publish Next from master
on:
  push:
    branches:
      - master
    paths:
      - 'src/**/*.ts?'
      - 'yarn.lock'
jobs:
  publish_next_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: pkg/ui/workspaces/cluster-ui/yarn.lock
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Publish Dry Run
      run: |
        echo "yarn version --prerelease --preid prerelease"
        echo "yarn publish --access public --tag next"
