name: Publish Release Version from Branch
on:
  push:
    branches:
      - 'release-*'
    paths:
      - 'src/**/*.ts?'
      - 'yarn.lock'
jobs:
  publish_release_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Get base branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Build
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Publish Dry Run
      run: |
        echo "yarn version --minor"
        echo "yarn publish --access public --tag ${{ steps.branch-name.outputs.base_ref_branch }}"
