name: Pull request to main
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*.ts?'
      - 'yarn.lock'
jobs:
  pull_request_checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Test
      run: yarn run test
